- name: Create git user with SSH key for deployment
  user:
    name: git
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    ssh_key_comment: git@{{ ansible_nodename }}
    groups: www-data
    append: yes

- name: user_data_contents
  shell: "cat /home/git/.ssh/id_rsa.pub"
  register: user_data_action

- debug: msg="git public key is {{ user_data_action.stdout }}"
