- name: Create git user with SSH key for deployment
  user:
    name: git
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    ssh_key_comment: git@{{ ansible_nodename }}
    append: yes

- name: user_data_contents
  shell: "cat /home/git/.ssh/id_rsa.pub"
  register: user_data_action
  changed_when: False

- debug: msg="git public key is {{ user_data_action.stdout }}"
  when: user_data_action.stdout is defined

- name: Add user www-data to group git
  user:
    name: www-data
    groups: git
    append: yes
