---

- name: Generate default locale
  locale_gen: name="{{ locale_lc_all }}" state=present

- name: Set default locale
  template:
        backup=yes
        src=etc/default/locale.j2
        dest=/etc/default/locale
        owner=root
        group=root
        mode=0644

- name: APT sources.list
  template:
        backup=yes
        src=etc/apt/sources.list.j2
        dest=/etc/apt/sources.list
        owner=root
        group=root
        mode=0644
  tags: packages

- block:
  - name: install apt requirements
    apt: pkg=aptitude
    tags: packages
  rescue:
    - name: Preious task failed, force aptitude install
      raw: apt-get update && apt-get -y install aptitude

- name: Ensure system packages are up to date
  apt:
    upgrade=safe
    update_cache={{ apt_update_cache }}
    cache_valid_time={{ apt_cache_valid_time }}
  tags: packages

- name: Ensure bash, OpenSSl, and libssl are the latest versions
  apt: name={{ item }} state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Ensure security updates are applied automatically
  apt: name={{ item }} state=latest
  with_items:
    - unattended-upgrades
  tags: packages

- name: basic utilities. htop, git, joe, vim, fail2ban, rpl
  apt: name={{ item }} state=latest
  with_items:
    - htop
    - git
    - joe
    - vim
    - rpl
  tags: packages

- name: Install fail2ban
  apt: name=fail2ban state=latest
  when: fail2ban_install
  tags: packages

- include: ntp.yml
  when: ntp_enable

- name: Python environment install
  include: "python.yml"
  when: python_env_install

- name: PHP environment install
  include: "php_{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
  when: php_env_install

# Nginx
- name: nginx install
  apt: name={{ item }} state=latest
  with_items:
    - nginx
  tags: packages, nginx

- name: make sure nginx root exists
  file: path={{ nginx_default_root }} state=directory
      owner=root
      group=root
      mode=0755

- name: nginx default configuration
  template:
        backup=yes
        src=etc/nginx/sites-available/default.j2
        dest=/etc/nginx/sites-available/default
        owner=root
        group=root
        mode=0644
  notify:
    - reload nginx
  tags: nginx

- name: nginx default.conf directory
  file: path=/etc/nginx/sites-available/default.conf state=directory

# Supervisord.org
- name: supervisord
  apt: name={{ item }} state=latest
  with_items:
    - supervisor
  tags: packages

- name: supervisor configuration
  template:
        backup=yes
        src=etc/supervisor/supervisord.conf.j2
        dest=/etc/supervisor/supervisord.conf
        owner=root
        group=root
        mode=0640
  notify:
  - reread supervisor

- name: supervisor nginx configuration
  template:
        backup=yes
        src=etc/nginx/sites-available/default.conf/supervisor.conf.j2
        dest=/etc/nginx/sites-available/default.conf/supervisor.conf
        owner=root
        group=root
        mode=0644
  notify:
  - reload nginx
  when: supervisor_web_enabled

- name: ensure supervisor is running
  service: name=supervisor state=started

# Monit
- name: monit
  apt: name={{ item }} state=latest
  with_items:
    - monit
  tags: packages

- name: monit configuration
  template:
        backup=yes
        src=etc/monit/conf.d/{{ item }}.j2
        dest=/etc/monit/conf.d/{{ item }}
        owner=root
        group=root
        mode=0644
  with_items:
      - basic_conf
      - nginx
      - php-fpm
      - supervisor
      - system_resources
  notify:
    - reload monit
  when: monit_install

- name: monit nginx configuration
  template:
        backup=yes
        src=etc/nginx/sites-available/default.conf/monit.conf.j2
        dest=/etc/nginx/sites-available/default.conf/monit.conf
        owner=root
        group=root
        mode=0644
  notify:
    - reload nginx
  when: monit_install and monit_web_enabled

- name: remove monit nginx configuration
  file:
    path=/etc/nginx/sites-available/default.conf/monit.conf
    state=absent
  notify:
    - reload nginx
  when: not (monit_install and monit_web_enabled)

# Munin
- name: munin
  apt: name={{ item }} state=latest
  with_items:
    - munin
  tags: packages
  when: munin_install

- name: munin configuration
  template:
        backup=yes
        src=etc/nginx/sites-available/default.conf/munin.conf.j2
        dest=/etc/nginx/sites-available/default.conf/munin.conf
        owner=root
        group=root
        mode=0644
  notify:
    - reload nginx
  when: munin_install and munin_web_enabled

- name: remove munin nginx configuration
  file:
    path=/etc/nginx/sites-available/default.conf/munin.conf
    state=absent
  notify:
    - reload nginx
  when: not (munin_install and munin_web_enabled)

- include: git-user.yml
