---

- name: Set default locale
  template:
        backup=yes
        src=etc/default/locale.j2
        dest=/etc/default/locale
        owner=root
        group=root
        mode=0644

- name: Generate default locale
  locale_gen: name="{{ locale_lc_all }}" state=present

# APT
- name: apt
  include: apt.yml
  when: apt_enable
  tags:
    - packages
    - apt

- name: Install fail2ban
  apt: name=fail2ban state=latest
  when: fail2ban_install|bool
  tags: packages

- include: ntp.yml
  when: ntp_enable|bool

- name: Python environment install
  include: "python.yml"
  when: python_env_install|bool

- name: PHP environment install
  include: "php_{{ ansible_distribution }}_{{ ansible_distribution_version }}_{{ ansible_distribution_release }}.yml"
  when: php_env_install|bool

# Nginx
- name: nginx install
  apt:
    name:
    - nginx
    state: latest
  tags: packages, nginx

- name: make sure nginx root exists
  file: path={{ nginx_default_root }} state=directory
      owner=root
      group=root
      mode=0755

- name: nginx default configuration
  template:
        backup=yes
        src=etc/nginx/sites-available/default.j2
        dest=/etc/nginx/sites-available/default
        owner=root
        group=root
        mode=0644
  notify:
    - reload nginx
  tags: nginx

- name: nginx default.conf directory
  file: path=/etc/nginx/sites-available/default.conf state=directory

# Supervisord.org
- name: supervisord
  apt:
    name:
    - supervisor
    state: latest
  tags: packages
  when: supervisor_install|bool

- name: supervisor configuration
  template:
        backup=yes
        src=etc/supervisor/supervisord.conf.j2
        dest=/etc/supervisor/supervisord.conf
        owner=root
        group=root
        mode=0640
  notify:
  - reread supervisor

- name: supervisor nginx configuration
  template:
        backup=yes
        src=etc/nginx/sites-available/default.conf/supervisor.conf.j2
        dest=/etc/nginx/sites-available/default.conf/supervisor.conf
        owner=root
        group=root
        mode=0644
  notify:
  - reload nginx
  when: supervisor_install|bool and supervisor_web_enabled|bool

- name: ensure supervisor is running
  service: name=supervisor state=started
  when: supervisor_install|bool

# Monit
- name: monit
  include: monit.yml
  tags: monit

# Munin
- name: munin
  apt:
    name:
    - munin
    state: latest
  tags: packages
  when: munin_install|bool

- name: munin configuration
  template:
        backup=yes
        src=etc/nginx/sites-available/default.conf/munin.conf.j2
        dest=/etc/nginx/sites-available/default.conf/munin.conf
        owner=root
        group=root
        mode=0644
  notify:
    - reload nginx
  when: munin_install|bool and munin_web_enabled|bool

- name: remove munin nginx configuration
  file:
    path=/etc/nginx/sites-available/default.conf/munin.conf
    state=absent
  notify:
    - reload nginx
  when: not (munin_install|bool and munin_web_enabled|bool)

- include: git-user.yml
  tags: git-user
