---
- name: nginx install
  apt:
    name:
    - nginx
    state: latest
  tags: packages, nginx

- name: make sure nginx root exists
  file:
    path: "{{ nginx_default_root }}"
    state: directory
    owner: root
    group: root

- name: nginx default configuration
  template:
        backup=yes
        src=etc/nginx/sites-available/default.j2
        dest=/etc/nginx/sites-available/default
        owner=root
        group=root
        mode=0640
  notify:
    - reload nginx
  tags: nginx

- name: nginx default.conf directory
  file: path=/etc/nginx/sites-available/default.conf state=directory
