- name: php environment
  apt:
    name:
    - php5-common
    - php5-cli
    - php5-fpm
    - php5-cgi
    state: latest
  tags: packages

- name: Set short_open_tag
  lineinfile:
      dest=/etc/php5/fpm/php.ini
      state=present
      regexp='^short_open_tag = Off'
      line='short_open_tag = On'
