- name: python environment
  apt:
    name:
    - python-pip
    - python-virtualenv
    - python-dev
    state: latest
  tags: packages

- name: python3 environment
  apt:
    name:
    - python3-pip
    - python3-dev
    - python3-venv
    state: latest
  tags: packages
