- name: python environment
  apt:
    name:
    - python-pip
    - python-virtualenv
    - python-dev
    state: latest
  when: python2_env_install|bool
  tags: packages

- name: python3 environment
  apt:
    name:
    - python3-pip
    - python3-dev
    - python3-venv
    - virtualenv
    state: latest
  when: python_env_install|bool
  tags: packages

- name: python3 as default python
  apt:
    name:
    - python-is-python3
    state: latest
  when: python_env_install|bool
  ignore_errors: yes
  tags: packages
