- name: python environment
  apt: name={{ item }} state=latest
  with_items:
    - python-pip
    - python-virtualenv
    - python-dev
  tags: packages

- name: python3 environment
  apt: name={{ item }} state=latest
  with_items:
    - python3-pip
    - python3-dev
  tags: packages
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release != 'zesty' and ansible_distribution_release != 'bionic'

- name: python3 environment
  apt: name={{ item }} state=latest
  with_items:
    - python3-pip
    - python3.6-dev
  tags: packages
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'zesty'

- name: "python3 virtualenv Ubuntu trusty"
  apt: name={{ item }} state=latest
  with_items:
    - python3.4-venv
  tags: packages
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

- name: "python3 virtualenv Ubuntu xenial"
  apt: name={{ item }} state=latest
  with_items:
    - python3.5-venv
  tags: packages
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- name: "python3 virtualenv Ubuntu zesty"
  apt: name={{ item }} state=latest
  with_items:
    - python3.6-venv
  tags: packages
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'zesty'

- name: "python3 virtualenv Ubuntu bionic"
  apt: name={{ item }} state=latest
  with_items:
    - python3-venv
  tags: packages
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'bionic'
